# Generated by Django 5.0.2 on 2024-10-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=50)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
                ('nota', models.FloatField(max_length=2)),
                ('genero', models.CharField(choices=[('A', 'Action'), ('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance'), ('H', 'Horror')], max_length=50)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PUCMais.topmovie')),
            ],
        ),
    ]
