# Generated by Django 5.1.2 on 2024-10-25 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCMais', '0002_topmovie_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genero',
            field=models.CharField(choices=[('A', 'Ação'), ('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance'), ('H', 'Horror')], max_length=50),
        ),
    ]
