# Generated by Django 5.1.3 on 2024-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_discipline_course_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
