# Generated by Django 5.1.2 on 2024-11-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_discipline_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
        ),
    ]
