# Generated by Django 5.1.3 on 2024-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_exam_courses_exam_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='discipline',
        ),
        migrations.AddField(
            model_name='exam',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
