# Generated by Django 5.1.2 on 2024-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_exam_discipline_exam_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
