# Generated by Django 5.1.3 on 2024-12-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_discipline_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='list',
        ),
        migrations.AddField(
            model_name='question',
            name='lista',
            field=models.ManyToManyField(to='app.list'),
        ),
    ]
