# Generated by Django 5.1.2 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_question_list_question_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isadvanced',
            field=models.BooleanField(default=False),
        ),
    ]
